### ISSUE TITLE
Inconsistent arguments in some helper functions

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api-tests#100]
For example, in `assert_dtype`, the `in_dtype` is before `out_dtype` https://github.com/data-apis/array-api-tests/blob/511929cebea939f137f910b4a68ddbce42f69611/array_api_tests/pytest_helpers.py#L83-L90 in `assert_keepdimable_shape` the `in_shape` is after `out_shape` https://github.com/data-apis/array-api-tests/blob/511929cebea939f137f910b4a68ddbce42f69611/array_api_tests/pytest_helpers.py#L181-L189

By the way, it would be useful to have small docstrings for the various helper functions.

**Comment by honno** [comment]
Ah this is a bit awkward, because say `ph.assert_dtype()` will always use `in_dtype` both for its error messages e.g. `... [func(uint8, int16)]`, and sometimes use it for infer `expected`. In say `ph.assert_keepdimable_shape()`, `in_shape` is indeed always use as the "expected".

Still yeah it'd be a good idea to to review the args order a bit, and definitely write some docs. I hadn't spent too much time on documenting utils because I end up removing half the ones I write anyway, but now would be a good time to regroup.
