### ISSUE TITLE
Don't require functions to raise a certain error for an unsupported number of inputs

### ISSUE THREAD

**Issue by pmeier** [data-apis/array-api-tests#13]
https://github.com/data-apis/array-api-tests/blob/6e3684b7948564b3ecd69f5b066aaf9c722120ec/array_api_tests/test_signatures.py#L182

requires a function to raise either a `TypeError` or a `ValueError` in case it is called with an unsupported number of positional arguments. This is not true for PyTorch:

```python
>>> import torch
>>> torch.Tensor.__add__()
NotImplemented
```

There is nothing about this [in the specification](https://data-apis.org/array-api/latest/API_specification/array_object.html#add-self-other).

**Comment by asmeurer** [comment]
The slash in the definition in the spec means that both of the arguments are positional only, so that they both have to be provided. Anyway, it's odd that pytorch would allow `__add__()` with no arguments, as that can never actually be called by Python. Seems like a (mostly inconsequential) bug in pytorch.
