### ISSUE TITLE
Enquiry: How do you re-run tests with certain inputs to reproduce a failure?

### ISSUE THREAD

**Issue by simonetgordon** [data-apis/array-api-tests#150]
In ivy, we use the `@example` decorator to reproduce test failures. However, it would seem this is only possible if the data is generated in `@given` rather than in the main body of the test function. Most of the array-api tests use `data.draw` in the main body of the test function, so this method is not possible.

I also notice that no seeds for reproducing a run are written in the hypothesis output for array-api tests, nor does the `print_blob` option seem to be activated.

Am I incorrect on any of these points? Are there other ways of testing with certain inputs that I have not gleamed from the hypothesis website? 

Thanks in advance!

**Comment by asmeurer** [comment]
I would love to see `draw` usage reduced when possible. Sometimes it's not very easy, though, and requires writing very complex strategies. It would be nice if `@example` could handle these situations better. That's really a feature request for the hypothesis developers. 

Even so, how were you planning to do this? By patching `@example` decorators onto existing tests? 

> I also notice that no seeds for reproducing a run are written in the hypothesis output for array-api tests, nor does the print_blob option seem to be activated.

print_blob seems to be enable automatically when hypothesis thinks it is running on a CI (see https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.print_blob). You can enable it by setting the `CI` environment variable. 

I'd be careful using seeds. The exact behavior of a seed will change across different hypothesis or test suite versions. Seeds are designed to reproduce a run for a single test session, not for ensuring a specific example is regression tested.

**Comment by simonetgordon** [comment]
Hi @asmeurer, thanks for the response. I wasn't planning on changing anything to make `@example` to work, I was just curious to know how you guys run tests with specific inputs. The blob method seems to be the best.

Thanks for the heads-up about using seeds too!

**Comment by asmeurer** [comment]
For now we don't, partly because the usage of `data` makes it impossible, and partly because we don't really try to check any specific examples. We just implement tests against the spec and hypothesis will (eventually) generate an example for any given input. 

Maybe there's a need for libraries to be able to add specific regression examples? I'm not sure how this should be implemented if so. And like I said, this would also require either removing `data` (which I would like anyway), or adding some way to hypothesis do examples with `data` (which I would also like anyway).
